### ISSUE TITLE
bayer demosaic?

### ISSUE THREAD

**Issue by dschneiderch** [swarm-lab/Rvision#13]
Could this provide access to the bayer demosiac function in the opencv library? I didn't see the function when I looked through the R package, and it was unclear if the bayer demosaic in the opencv library was even part of the RopencvLite install. I'm very new to opencv but am looking to integrate the demosaic process into my R pipeline if possible. I haven't seen any other options. Thanks!

**Comment by sjmgarnier** [comment]
@dschneiderch This function is not accessible through the current version of Rvision, but it should be easy to implement. However, the function documentation on the OpenCV website (https://docs.opencv.org/3.4.3/d7/dbd/group__imgproc.html#gabd0f8509ef654d2b8e0a987635b8326d) is not clear on the values that some of the parameters (code and dcn) can take. Without more details, I don't think it is reasonable to port the function to Rvision at the moment because I can't know if argument checks are required to make sure the function doesn't crash.

**Comment by dschneiderch** [comment]
ok, thanks for the response and adding it to your enhancement list!
