### ISSUE TITLE
Subsetting/indexing conventions

### ISSUE THREAD

**Issue by dselivanov** [swarm-lab/Rvision#16]
Hi Simon. 
Thanks for the wonderful package! (and ROpvenCVlite!)

This is not an issue, but rather small concern regarding certain conventions. At the moment `subImage` uses "bottom left" as a starting point for cropping image. However widely used standard is to use top left (as it is done in openCV and all python libraries). 
I see it is wrapped here: https://github.com/swarm-lab/Rvision/blob/9323f0a12a95f9fcbdf74c9ac17cb5b1db23e01f/src/Image.h#L625)

I think in long term it will be beneficial to stick to OpenCV conventions. Same with 0/1 indexing...

**Comment by sjmgarnier** [comment]
Hi Dmitriy,

Thanks for your kind words. I was tired of switching back and forth between R for most of my work and Python for computer vision, so I took the jump and decided to build my own computer library vision for R.

I struggled with that point when I started working on Rvision. The main issue is that the graphics devices in R are all "bottom left" based and I was concern this would confuse users when using the `plot` function and its derivatives. The issue is similar with 0/1 indexing. R uses 1 indexing and so I tried to match that convention. 

As far as I am concerned, I have no preference but I'm trying to put myself in the shoes of a typical R user (especially one who doesn't have experience with other languages) and I make my decisions based on this mostly. I'm happy to keep the discussion going, see if we can find a good way to resolve this at some point.
